apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-webhook-bunny.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cert-manager-webhook-bunny.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "cert-manager-webhook-bunny.selectorLabels" . | nindent 4 }}
